# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20160715_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(default='', max_length=255)),
                ('content', models.TextField(default='')),
                ('url', models.CharField(default='0', max_length=255)),
            ],
        ),
    ]
