# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('color', models.CharField(default='', max_length=7)),
                ('logo', models.ImageField(default=0, upload_to='services/')),
                ('url', models.CharField(default='0', help_text='0 for No Url', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='notice',
            name='url',
            field=models.CharField(default='0', help_text='0 for no Url', max_length=255),
        ),
    ]
