# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20160719_0222'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='associates',
            new_name='associate',
        ),
    ]
