# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20160719_0226'),
    ]

    operations = [
        migrations.CreateModel(
            name='query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('email', models.CharField(default='', max_length=40)),
                ('subject', models.CharField(default='', max_length=255)),
                ('service', models.CharField(default='', max_length=40)),
                ('query', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='kind',
            field=models.IntegerField(choices=[(0, 'HR'), (1, 'IT'), (2, 'FINANCE')], default=0),
        ),
    ]
